version: '3'
services:
  nakama:
    container_name: nakama
    image: heroiclabs/nakama:latest
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - > 
          /nakama/nakama migrate up --database.address "cederik:yguL2tRnkZ5IXOWO@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/first-bird-2784.defaultdb" &&    
          exec /nakama/nakama --name nakama1 --database.address "cederik:yguL2tRnkZ5IXOWO@free-tier.gcp-us-central1.cockroachlabs.cloud:26257/first-bird-2784.defaultdb"
    restart: always
    volumes:
      - ./:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
volumes:
  nakama: